language: php

php:
   - 7.3

install:
   - composer install

script:
   - composer run test:unit -- --coverage-clover ./clover.xml

after_success:
   - composer require --dev satooshi/php-coveralls:1.*
   - vendor/bin/coveralls -v --coverage_clover=./clover.xml
